version: '3.9'

services:

  generator:
    build:
      context: src
      dockerfile: Dockerfile
    volumes:
      - ./src:/code
    ports: 
      - "8000:8000"
    networks:
      - forapi
  
networks:
  forapi:
    driver: bridge