{
 "title": "New dashboard",
 "time": { "from": "2024-07-27T17:10:06.864Z", "to": "2024-07-28T22:15:39.822Z" },
 "panels": [
  {
   "title": "Active Users",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select count(distinct session_id) from clickstream where event_time between now() - INTERVAL 1000 MINUTE and now() + INTERVAL 1000 MINUTE"
    }
   ]
  },
  {
   "title": "Average Session Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH SessionDurations AS (\n    SELECT\n        session_id,\n        (max(event_time) - min(event_time)) AS session_duration\n    FROM\n        clickstream\n    where date(event_time) = date(now())\n    GROUP BY\n        session_id\n)\n\nSELECT\n    avg(session_duration)/60 AS avg_session_duration\nFROM\n    SessionDurations;"
    }
   ]
  },
  {
   "title": "Source of traffic",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select channel, sum(cnt) from source_of_traffic where traffic_date=date(now()) group by traffic_date, channel"
    }
   ]
  },
  {
   "title": "Popular devices",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select brand, sum(cnt) from top_brand where brand_date=date(now()) group by brand_date, brand"
    }
   ]
  },
  {
   "title": "% of user completing order",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 1, "y": 4 },
   "targets": [
    {
     "rawSql": "WITH GoalEvents AS (\n    SELECT\n        user_id\n    FROM\n        clickstream\n    WHERE\n        event_name = 'CompleteOrder' and\n        date(event_time) = date(now())\n)\nSELECT\n    (SELECT COUNT(DISTINCT user_id) FROM GoalEvents) * 100.0 / COUNT(DISTINCT user_id) AS conversion_rate\nFROM\n    clickstream;\n"
    }
   ]
  },
  {
   "title": "Traffic per country",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 7 },
   "targets": [
    {
     "rawSql": "select country, sum(cnt) from top_country where country_date=date(now()) group by country_date, country"
    }
   ]
  },
  {
   "title": "Events per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select event_date, sum(cnt) from event_per_minute where date(event_date) = date(now()) group by event_date"
    }
   ]
  }
 ]
}